name: lovemaking-art
favicon: null
layout_spectrum: 0.011441647773608565
typography_spectrum: 0.10073623084463179
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.043643902987241745
  lightness: 0.8593810428865254
  saturation: 0.5432563328649849
  rhythmicContrast: 0.9150710923131555
purpose: []
